### ISSUE TITLE
Error setting RS-232 mode: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by DiDu0815** [cbrake/linux-serial-test#11]
First, thanks for the code, it is very useful. I use it on Ubuntu 16.04.
On each run, regardless of parameters used, I get the message above. The code seems to work well however; I can verify it using a scope attached to RX-TX on the loopback plug.
Simple example to produce the message: **"sudo ./linux-serial-test -p /dev/ttyS0"**.
The message ist not in the source code, so it must be thrown from the includes. Any idea where this comes from and how to avoid it?

**Comment by andy-shev** [comment]
One of the IOCTLs is not supported by your system.
I would suspect this one:

	ioctl(_fd, TIOCGRS485, &rs485)

**Comment by cbrake** [comment]
there may be some way to detect if the platform supports RS485, and then only call those ioctls if appropriate.

**Comment by DiDu0815** [comment]
True, the system has RS-232 only. So if any message in this case the "error" should be better something more like "informational", to avoid causing concerns at user side.

**Comment by cbrake** [comment]
pull requests are welcome.
