### ISSUE TITLE
Testing MODEM signals?

### ISSUE THREAD

**Issue by nurbles** [cbrake/linux-serial-test#12]
I need to check for support of all of the signals, not just CTS/RTS.  I will attempt to add a modem signal test to the code (thanks for sharing, by the way!) but I'm not sure I can make it work and, since its purpose is to test the signal lines and their support -- I will have trouble knowing if I have messed up, or if I'm working on a machine that doesn't have one or more of the lines.

It would also be great if the program could list all existing serial devices when the command line is empty (or a specific option is used).  Surprisingly, there appears to be no tool that does that for linux!

Is it wrong to hope for help adding these things?

**Comment by cbrake** [comment]
on linux, you can run the following command to list available USB serial ports:

`ls /dev/ttyUSB*`

For built in serial ports, the naming is not as standard, so I hesitate to try to build something into the app -- typically requires some level of platform knowledge that the app has no way of knowing. Basically, to work at this level, you need to understand the system you are working with.

Pull requests are welcome if you want to add support for other handshaking lines.
