### ISSUE TITLE
An example for two ports

### ISSUE THREAD

**Issue by yegorich** [cbrake/linux-serial-test#14]
Could you add commands examples for two ports? Should it be like this:

**Sender**
`linux-serial-test -s -e -p /dev/ttyO0 -r -c -b 460800`

**Receiver**
`linux-serial-test -s -e -p /dev/ttyO1 -t -c -l 250 -b 460800`

**Comment by cbrake** [comment]
What you suggested looks right to me, but I have not tested it. If you have tested the below, and want to send a pull request with documentation changes, I'd be glad to merge.

Please confirm you have tested it.

Cliff

**Comment by yegorich** [comment]
I have tested these commands with two OMAP ports and one OMAP connected to one FTDI port.
