### ISSUE TITLE
Full RS485 support

### ISSUE THREAD

**Issue by yegorich** [cbrake/linux-serial-test#18]
To enable the full RS485 support, we need to be able to configure the following parameters:

- RTS on send (bool)
- RTS after send (bool)
- RTS delay before send (int)
- RTS delay after send (int)
- Receive during sending data (bool)

If any of these options is provided, turn RS485 on. How would you name the parameters, especially as we already have -q option?

See [rs485conf](https://github.com/mniestroj/rs485conf) project for more information.

**Comment by LeSpocky** [comment]
> Not sure if getopt can do that?

With `_GNU_SOURCE` you could use `getopt_long()` or `getopt_long_only()`.
