### ISSUE TITLE
TIOCGSERIAL failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by ebi-droid** [cbrake/linux-serial-test#31]
When I try to sart the app:
./linux-serial-test -s -e -p /dev/ttyUSB0 -c -l 250
Linux serial test app

I get the following error:
TIOCGSERIAL failed: Inappropriate ioctl for device

how to solve it ?

**Comment by cbrake** [comment]
can you try commenting out this line: 

https://github.com/cbrake/linux-serial-test/blob/master/linux-serial-test.c#L615

**Comment by dwillmore** [comment]
That solved it for me.  CH340G adapter here.  Thank you!

**Comment by cbrake** [comment]
let me know if any concerns with this:

https://github.com/cbrake/linux-serial-test/commit/0685fc53870f52d38af82bdcddaeb6dc0182fb72

I think this is better behavior.
