### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sinsalo** [cbrake/linux-serial-test#36]
First of all: Thx for this project

I use the main method in a recursive way and noticed, that the global variable _write_data is never freed

Regards

**Comment by cbrake** [comment]
does this fix your issue?

https://github.com/cbrake/linux-serial-test/commit/9cf666347e643293eae625833fb33a6525399d9f

**Comment by sinsalo** [comment]
yes, perfect

**Comment by cbrake** [comment]
thanks for reporting!
