### ISSUE TITLE
Sending custom data over UART

### ISSUE THREAD

**Issue by karthikkumarb** [cbrake/linux-serial-test#49]
Hi, 

I need to send some custom data like "\x00\x13\x00" over UART using this code, Can you please help me how to send some custom data?

Thanks,
Karthik

**Comment by andy-shev** [comment]
Basic idea is to have the port to be set in a `raw` mode. In this case the TTY layer won't mangle any character on wire (it might be an exception fox XON/XOFF case, but anyway it's highly recommended to have a HW flow control).

P.S. I dunno why you need this code to be used, but in shell the `printf ...` will do the job.

**Comment by cbrake** [comment]
You can also use the following in a various programming languages:

- https://pyserial.readthedocs.io/en/latest/pyserial.html
- https://pkg.go.dev/go.bug.st/serial

Or simply modify this program to put your data in the buffer that gets sentout.
