### ISSUE TITLE
Use different ports for RX and TX

### ISSUE THREAD

**Issue by Harvie** [cbrake/linux-serial-test#55]
Hello,
i would like to use this to test connection between two serial ports (instead of just using loopback). can you please add such functionality?

Usecase:  i have two rs485 ports. if there is bad connection between rs485 line driver and connector, the loopback will work anyway, because rs485 uses single half duplex line for RX and TX (there is always loopback no matter what). therefore i need to connect two separate ports together to test it properly.

**Comment by cbrake** [comment]
Can you run two instances of the -- one on each port?

**Comment by Harvie** [comment]
Will that work out of the box? two instances facing each other?

**Comment by cbrake** [comment]
It's been a long time since I've done this -- but I think if one instance generates a known counting pattern, and the other instance is looking for the same pattern, it should be OK. Give it a try and let us know how it goes ...

**Comment by andy-shev** [comment]
Just a note: The first one to start is Rx side (for obvious reasons).

**Comment by cbrake** [comment]
I think the solution proposed is reasonable, closing ...
